const PermissionEmpty = {
  id: 0,
  admin_id: 0,
  permission: "",
  status: "",
};
const WalletTransactionEmpty = {
  amount: "",
  created_at: "",
  customer_id: null,
  customer_order_id: null,
  id: null,
  paymentType: "",
  updated_at: "",
};
const VendorEmpty = {
  id: null,
  created_at: null,
  email: "",
  profile: "",
  password: "",
  vendorName: null,
  contactInformation: "",
  address: "",
};
const RetainershipEmpty = {
  assignedTo: "",
  maxUses: "",
  created_at: "",
};
const MakeShipmentOrderEmpty = {
  packageType: "Express Shipments",
  paymentType: "On-Delivery",
  deliveryInstructions: "Call - 09054551017 When at gate",
  locationType: "Within-State",
  customerID: 0,
  orderType: "Logistics",
  origin: "Abuja",
  pickUp: {
    pickupAddress: "house 11, Kalas-Street, palmheights Luxury, lugbe",
    pickupState: "Abuja",
  },
  dropOff: {
    dropOffAddress: "Kalas Street, Palm Heights Luxury, lugbe, Abuja",
    dropOffState: "Abuja",
  },
};
const VendorItemEmpty = {
  id: null,
  image: "",
  name: "",
  description: "",
  created_at: null,
  price: "",
  vendor_item_category_id: "",
  vendor_id: "",
};

const CouponEmpty = {
  id: "",
  validUntill: "",
  validFrom: "",
  forUseBy: "",
  status: "",
  couponType: "",
  percentageDiscount: "",
  reductionAmount: "",
  code: "",
  createdAt: "",
  maxUses: "",
  currentUses: "",
};
const DriverEmpty = {
  id: 0,
  created_at: "",
  updated_at: "",
  firstName: "",
  phone_number: "",
  lastName: "",
  email: "",
  profile: null,
  city: "",
  state: "",
  type: "",
  address: "",
  title: "",
  password: "",
  gender: "",
  licenseNumber: "",
  licenseExpiration: "",
  vehicleMake: "",
  vehicleModel: "",
  licensePlate: "",
  insurance: "",
  allowEdit: 1,
};
const CustomerEmpty = {
  id: null,
  email: "",
  firstName: "",
  lastName: "",
  type: "",
  title: "",
  gender: "",
  phone_number: "",
  address: "",
  profile: "",
  city: "",
  state: "",
  created_at: "",
  updated_at: "",
  email_verified_at: null,
  verify_token: null,
};

const AdminEmpty = {
  id: 37,
  email: "",
  firstName: "",
  lastName: "",
  type: "",
  title: "",
  gender: "",
  phone_number: "",
  address: "",
  profile: "",
  city: "",
  state: "",
  created_at: "",
  updated_at: "",
  email_verified_at: null,
  verify_token: null,
  permissions: [PermissionEmpty],
};
const ActivityEmpty = {
  id: 0,
  user_id: 0,
  user_type: "",
  data_id: 0,
  data_type: "",
  description: "",
  created_at: "",
};
const PaymentEmpty = {
  customer_id: "",
  id: "",
  amount: "",
  currency: "",
  payment_method: "",
  status: "",
  paystack_refrence_id: "",
  created_at: "",
};
const DeliveryEmpty = {
  customer: CustomerEmpty,
  id: "",
  customer_order_id: "",
  customer_order: OrderEmpty,
  tracking_number: "0",
  status: "",

  pickup_date: "",
  delivery_date: "",
  driver: DriverEmpty,
  image: "",
};
const WarehouseEmpty = {
  id: 0,
  name: "",
  location: "",
  capacity: 0,
  created_at: "",
  updated_at: "",
};
var OrderEmpty = {
  customer: CustomerEmpty,
  id: 0,
  payment_id: "",
  location_type: "Inter-State",
  delivery_instructions: "",
  packageType: "",
  origin: "",
  request_description: "",
  total_payment: "",
  delivery: DeliveryEmpty,
  payment_method: "",
  shipment_description: "",
  pickup_address: "",
  pickup_state: "",
  status: "",
  dropOff_state: "",
  dropOff_address: "",
  created_at: "",
};

const InvoiceEmpty = {
  customer: CustomerEmpty,
  customer_order: OrderEmpty,
  payment: PaymentEmpty,
  customer_order_id: 0,
  warehouse: WarehouseEmpty,
  id: 0,
  customer_id: 0,
  created_at: "",
};

const InventoryEmpty = {
  customer: CustomerEmpty,
  id: "",
  warehouse: WarehouseEmpty,
  warehouse_id: 0,
  product_description: "",
  quantity: 2,
  created_at: "",
  image: "",
};

const InventoryDeliveryRequest = {
  avilableQuantity: 0,
  inventory_id: null,
  inventory: InventoryEmpty,
  id: 0,
  status: "pending",
  requestQuantity: 0,
  deliveryAddress: "",
  customer: CustomerEmpty,
  requestDescription: "",
};

export const defaultTypes = {
  PermissionEmpty,
  DriverEmpty,
  CustomerEmpty,
  AdminEmpty,
  ActivityEmpty,
  VendorEmpty,
  PaymentEmpty,
  DeliveryEmpty,
  InventoryEmpty,
  OrderEmpty,
  WarehouseEmpty,
  InvoiceEmpty,
  CouponEmpty,
  InventoryDeliveryRequest,
  WalletTransactionEmpty,
  RetainershipEmpty,
  VendorItemEmpty,
  MakeShipmentOrderEmpty,
};
